### ISSUE TITLE
issue load metro when run android 

### ISSUE THREAD

**Issue by nguyenthetuan** [callstack/super-app-showcase#47]
when i run android metro for Package Host not load 
![Screenshot 2023-06-19 at 3 16 54 PM](https://github.com/callstack/super-app-showcase/assets/40887379/daee9436-b164-4c4b-b7d4-82eccf038f27)

**Comment by jbroma** [comment]
Hi @nguyenthetuan 

Could you please describe the issue in more detail? I'm not sure how metro fits into the picture here.

**Comment by DiegoAPG** [comment]
I get the same error when i try compile the proyect 

<img width="347" alt="image" src="https://github.com/callstack/super-app-showcase/assets/29066401/7b541a00-b8de-453f-9b27-4fe45f17b534">

**Comment by jbroma** [comment]
Hi @DiegoAPG,

please tell me the exact steps you've done so I can reproduce this, thanks!

**Comment by jbroma** [comment]
Looking back, this is almost certianly caused by running `metro` (via `yarn start`) instead of `webpack` (via `yarn webpack-start`). As Re.Pack uses `webpack` underneath, the correct way to start the dev server is with `yarn webpack-start`.

If the issue persists despite the above, please open new issue with that, thanks!
